Add: CW-09 Workload Implementation
Aemilivs/2201-SAD-Bot-Trader pull request #24
Opened 2022-03-06 16:59 UTC by Sol-Mane

Closes #7 
Closes #8 
Closes #19
Closes #20 
Closes #21 
Closes #22 
Closes #23

2022-03-06 17:07 UTC, Sol-Mane commented
Closes #2

2022-03-06 20:25 UTC, Feynman43 approved these changes
Agree with introducing GUI as submodule

2022-03-09 08:40 UTC, Aemilivs commented on AUTHORS
> +         Petr Svarny   <petr.s@praguecollege.cz>
Our lector is a great person, but I doubt we will be able to get evaluated by him if we list him as an author :)

2022-03-09 08:41 UTC, Aemilivs commented on LICENSE
> +         Petr Svarny   <petr.s@praguecollege.cz>
Same concern as in AUTHORS

2022-03-09 08:42 UTC, Aemilivs requested changes
I believe we should exclude Petr from authors of the project, since he is a professor leading the subject this project is purposed for and is supposed to put a mark on this project.

2022-03-11 08:26 UTC, Sol-Mane commented
I don't have an opinion on Petr's authorship, but as nobody else voiced his opinion I'll keep it in. I'm open to an MR that fixes that.

2022-03-11 08:26 UTC, merged